/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MetaWorkspaceNFTInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addToWhitelist"
      | "approve"
      | "balanceOf"
      | "getApproved"
      | "getContentType"
      | "getCreatorContent"
      | "getRoomContent"
      | "getRoomStats"
      | "getTotalSupplyByType"
      | "getVideoNFT"
      | "getVideoNFTsByRoom"
      | "getVoiceNFT"
      | "getVoiceNFTsByRoom"
      | "hasAccess"
      | "isApprovedForAll"
      | "mintVideoNFT"
      | "mintVoiceNFT"
      | "name"
      | "owner"
      | "ownerOf"
      | "renounceOwnership"
      | "roomExists"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "supportsInterface"
      | "symbol"
      | "tokenByIndex"
      | "tokenOfOwnerByIndex"
      | "tokenURI"
      | "tokensOfOwner"
      | "totalSupply"
      | "transferFrom"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "Approval"
      | "ApprovalForAll"
      | "NFTMinted"
      | "OwnershipTransferred"
      | "RoomActivity"
      | "Transfer"
      | "VideoNFTCreated"
      | "VoiceNFTCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addToWhitelist",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContentType",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorContent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoomContent",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoomStats",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalSupplyByType",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVideoNFT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVideoNFTsByRoom",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoiceNFT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoiceNFTsByRoom",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccess",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintVideoNFT",
    values: [
      AddressLike,
      string,
      BigNumberish,
      string,
      string[],
      string,
      string[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "mintVoiceNFT",
    values: [AddressLike, string, BigNumberish, string, string[], string]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "roomExists", values: [string]): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOfOwnerByIndex",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokensOfOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addToWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContentType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoomContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoomStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalSupplyByType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVideoNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVideoNFTsByRoom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoiceNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoiceNFTsByRoom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasAccess", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintVideoNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintVoiceNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "roomExists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenOfOwnerByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokensOfOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    username: string,
    grantedBy: AddressLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    username: string,
    grantedBy: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    username: string;
    grantedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTMintedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    creator: AddressLike,
    contentType: BigNumberish,
    roomId: string,
    ipfsHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    creator: string,
    contentType: bigint,
    roomId: string,
    ipfsHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    creator: string;
    contentType: bigint;
    roomId: string;
    ipfsHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoomActivityEvent {
  export type InputTuple = [
    roomId: string,
    user: AddressLike,
    activityType: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    roomId: string,
    user: string,
    activityType: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    roomId: string;
    user: string;
    activityType: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VideoNFTCreatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    creator: AddressLike,
    roomId: string,
    duration: BigNumberish,
    participantCount: BigNumberish,
    ipfsHash: string
  ];
  export type OutputTuple = [
    tokenId: bigint,
    creator: string,
    roomId: string,
    duration: bigint,
    participantCount: bigint,
    ipfsHash: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    creator: string;
    roomId: string;
    duration: bigint;
    participantCount: bigint;
    ipfsHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoiceNFTCreatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    creator: AddressLike,
    roomId: string,
    duration: BigNumberish,
    ipfsHash: string
  ];
  export type OutputTuple = [
    tokenId: bigint,
    creator: string,
    roomId: string,
    duration: bigint,
    ipfsHash: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    creator: string;
    roomId: string;
    duration: bigint;
    ipfsHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MetaWorkspaceNFT extends BaseContract {
  connect(runner?: ContractRunner | null): MetaWorkspaceNFT;
  waitForDeployment(): Promise<this>;

  interface: MetaWorkspaceNFTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addToWhitelist: TypedContractMethod<
    [tokenId: BigNumberish, username: string],
    [void],
    "nonpayable"
  >;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getContentType: TypedContractMethod<
    [tokenId: BigNumberish],
    [bigint],
    "view"
  >;

  getCreatorContent: TypedContractMethod<
    [creator: AddressLike],
    [bigint[]],
    "view"
  >;

  getRoomContent: TypedContractMethod<[roomId: string], [bigint[]], "view">;

  getRoomStats: TypedContractMethod<
    [roomId: string],
    [
      [bigint, bigint, bigint] & {
        totalContent: bigint;
        voiceCount: bigint;
        videoCount: bigint;
      }
    ],
    "view"
  >;

  getTotalSupplyByType: TypedContractMethod<
    [contentType: BigNumberish],
    [bigint],
    "view"
  >;

  getVideoNFT: TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [
        string,
        bigint,
        string,
        string,
        string[],
        string,
        bigint,
        boolean,
        string[]
      ] & {
        ipfsHash: string;
        duration: bigint;
        roomId: string;
        creator: string;
        participants: string[];
        summary: string;
        timestamp: bigint;
        isPrivate: boolean;
        whitelistedUsers: string[];
      }
    ],
    "view"
  >;

  getVideoNFTsByRoom: TypedContractMethod<[roomId: string], [bigint[]], "view">;

  getVoiceNFT: TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [string, bigint, string, string, bigint, boolean, string[], string] & {
        ipfsHash: string;
        duration: bigint;
        roomId: string;
        creator: string;
        timestamp: bigint;
        isPrivate: boolean;
        whitelistedUsers: string[];
        transcription: string;
      }
    ],
    "view"
  >;

  getVoiceNFTsByRoom: TypedContractMethod<[roomId: string], [bigint[]], "view">;

  hasAccess: TypedContractMethod<
    [tokenId: BigNumberish, username: string],
    [boolean],
    "view"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  mintVideoNFT: TypedContractMethod<
    [
      to: AddressLike,
      ipfsHash: string,
      duration: BigNumberish,
      roomId: string,
      participants: string[],
      summary: string,
      whitelistedUsers: string[]
    ],
    [bigint],
    "nonpayable"
  >;

  mintVoiceNFT: TypedContractMethod<
    [
      to: AddressLike,
      ipfsHash: string,
      duration: BigNumberish,
      roomId: string,
      whitelistedUsers: string[],
      transcription: string
    ],
    [bigint],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  roomExists: TypedContractMethod<[roomId: string], [boolean], "view">;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenByIndex: TypedContractMethod<[index: BigNumberish], [bigint], "view">;

  tokenOfOwnerByIndex: TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  tokensOfOwner: TypedContractMethod<[owner: AddressLike], [bigint[]], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addToWhitelist"
  ): TypedContractMethod<
    [tokenId: BigNumberish, username: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getContentType"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCreatorContent"
  ): TypedContractMethod<[creator: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRoomContent"
  ): TypedContractMethod<[roomId: string], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRoomStats"
  ): TypedContractMethod<
    [roomId: string],
    [
      [bigint, bigint, bigint] & {
        totalContent: bigint;
        voiceCount: bigint;
        videoCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalSupplyByType"
  ): TypedContractMethod<[contentType: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVideoNFT"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [
        string,
        bigint,
        string,
        string,
        string[],
        string,
        bigint,
        boolean,
        string[]
      ] & {
        ipfsHash: string;
        duration: bigint;
        roomId: string;
        creator: string;
        participants: string[];
        summary: string;
        timestamp: bigint;
        isPrivate: boolean;
        whitelistedUsers: string[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVideoNFTsByRoom"
  ): TypedContractMethod<[roomId: string], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getVoiceNFT"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [string, bigint, string, string, bigint, boolean, string[], string] & {
        ipfsHash: string;
        duration: bigint;
        roomId: string;
        creator: string;
        timestamp: bigint;
        isPrivate: boolean;
        whitelistedUsers: string[];
        transcription: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVoiceNFTsByRoom"
  ): TypedContractMethod<[roomId: string], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "hasAccess"
  ): TypedContractMethod<
    [tokenId: BigNumberish, username: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintVideoNFT"
  ): TypedContractMethod<
    [
      to: AddressLike,
      ipfsHash: string,
      duration: BigNumberish,
      roomId: string,
      participants: string[],
      summary: string,
      whitelistedUsers: string[]
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintVoiceNFT"
  ): TypedContractMethod<
    [
      to: AddressLike,
      ipfsHash: string,
      duration: BigNumberish,
      roomId: string,
      whitelistedUsers: string[],
      transcription: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "roomExists"
  ): TypedContractMethod<[roomId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenByIndex"
  ): TypedContractMethod<[index: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenOfOwnerByIndex"
  ): TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "tokensOfOwner"
  ): TypedContractMethod<[owner: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "NFTMinted"
  ): TypedContractEvent<
    NFTMintedEvent.InputTuple,
    NFTMintedEvent.OutputTuple,
    NFTMintedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RoomActivity"
  ): TypedContractEvent<
    RoomActivityEvent.InputTuple,
    RoomActivityEvent.OutputTuple,
    RoomActivityEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "VideoNFTCreated"
  ): TypedContractEvent<
    VideoNFTCreatedEvent.InputTuple,
    VideoNFTCreatedEvent.OutputTuple,
    VideoNFTCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VoiceNFTCreated"
  ): TypedContractEvent<
    VoiceNFTCreatedEvent.InputTuple,
    VoiceNFTCreatedEvent.OutputTuple,
    VoiceNFTCreatedEvent.OutputObject
  >;

  filters: {
    "AccessGranted(uint256,string,address)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "NFTMinted(uint256,address,uint8,string,string,uint256)": TypedContractEvent<
      NFTMintedEvent.InputTuple,
      NFTMintedEvent.OutputTuple,
      NFTMintedEvent.OutputObject
    >;
    NFTMinted: TypedContractEvent<
      NFTMintedEvent.InputTuple,
      NFTMintedEvent.OutputTuple,
      NFTMintedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RoomActivity(string,address,string,uint256)": TypedContractEvent<
      RoomActivityEvent.InputTuple,
      RoomActivityEvent.OutputTuple,
      RoomActivityEvent.OutputObject
    >;
    RoomActivity: TypedContractEvent<
      RoomActivityEvent.InputTuple,
      RoomActivityEvent.OutputTuple,
      RoomActivityEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "VideoNFTCreated(uint256,address,string,uint256,uint256,string)": TypedContractEvent<
      VideoNFTCreatedEvent.InputTuple,
      VideoNFTCreatedEvent.OutputTuple,
      VideoNFTCreatedEvent.OutputObject
    >;
    VideoNFTCreated: TypedContractEvent<
      VideoNFTCreatedEvent.InputTuple,
      VideoNFTCreatedEvent.OutputTuple,
      VideoNFTCreatedEvent.OutputObject
    >;

    "VoiceNFTCreated(uint256,address,string,uint256,string)": TypedContractEvent<
      VoiceNFTCreatedEvent.InputTuple,
      VoiceNFTCreatedEvent.OutputTuple,
      VoiceNFTCreatedEvent.OutputObject
    >;
    VoiceNFTCreated: TypedContractEvent<
      VoiceNFTCreatedEvent.InputTuple,
      VoiceNFTCreatedEvent.OutputTuple,
      VoiceNFTCreatedEvent.OutputObject
    >;
  };
}
